stages:
  - build
  - deploy

build_job:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploy_job:
  stage: deploy
  before_script:
    - 'which ssh || (apt-get update -y && apt-get install openssh-client -y)'
    - mkdir -p /home/tushar/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > /home/tushar/.ssh/id_rsa
    - chmod 600 /home/tushar/.ssh/id_rsa
    - ssh-keyscan 194.238.19.74 >> /home/tushar/.ssh/known_hosts
  script:
    - echo "Deploying to VPS"
    - rsync -avz -e "-i /home/tushar/.ssh/id_rsa" ./dist/ tushar@194.238.19.74:/home/tushardevelops-beatfeed/htdocs/beatfeed.tushardevelops.com
  only:
    - main
