stages:
  - build
  - deploy

build_job:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploy_job:
  stage: deploy
  before_script:
    - 'which ssh || (apt-get update -y && apt-get install openssh-client -y)'
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan 194.238.19.74 >> ~/.ssh/known_hosts
  script:
    - echo "Deploying to VPS"
    - scp -r ./dist/ tushar@194.238.19.74:/home/tushardevelops-beatfeed/htdocs/beatfeed.tushardevelops.com
  only:
    - main
